[options]
admin_passwd = admin123

db_host = localhost
db_port = 5432
db_user = odoo19
db_password = odoo19

db_template = template1

addons_path = C:\Users\Kasketa Tech\Desktop\Odoo19\odoo\odoo-19.0\addons,C:\Users\Kasketa Tech\Desktop\Odoo19\custom_addons